api: https://122e4e-mapbox.global.ssl.fastly.net
url: https://122e4e-mapbox.global.ssl.fastly.net
permalink: /:categories/:title
baseurl: /carto
pygments: true
version: 2.1.0
title: CartoCSS
rdiscount:
  extensions: [smart]
